version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - DB_HOST=postgres
      - DB_PORT=5430
      - DB_USER=postgres
      - DB_PASSWORD=123123
      - DB_NAME=postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123
      - POSTGRES_DB=postgres
